
from langchain.messages import HumanMessage, SystemMessage


from model.llm import get_llm
from schema.answer_schema import answerState


def check_answer(state: answerState) -> dict:
    """학생이 답변한 답변과 정답을 비교해서, 약점과 feedback을 분석한다."""
    #print("check_answer 들어옴")
    problem = state.problem
    correct_answer = state.correct_answer
    answer = state.answer
    problem_key_concepts = state.problem_key_concepts


    llm = get_llm()

    system_message = """
        You are an educational answer evaluator.

        Your task is to evaluate a student's answer to a given problem.

        You will be provided with:
        - problem: The problem generated by an LLM.
        - correct_answer: The correct answer that was stored when the problem was generated.
        - answer: The student's answer.
        - problem_key_concepts: The key concepts related to the problem.

        You must perform the following tasks:

        1. Determine whether the student's answer is correct.
        - Compare the student's answer with the correct answer.
        - Do not require the student's answer to be exactly identical to the correct answer.
        - For subjective or descriptive answers, judge whether the student's answer has the same essential meaning as the correct answer.
        - For mathematical or objective answers, judge the actual correctness of the answer.
        - Do not mark an answer as incorrect merely because of differences in wording, formatting, or expression.

        2. Provide feedback when necessary.
        - If the answer is incorrect, briefly explain what is wrong and what the student should understand.
        - If the answer is partially correct, explain what was correct and what needs improvement.
        - If the answer is correct, provide a short positive comment.
        - Feedback should be appropriate for an elementary school student.
        - Do not give unnecessarily long explanations.

        3. Identify conceptual weaknesses.
        - Use problem_key_concepts as the reference for the concepts required to solve the problem.
        - If the student's answer indicates a lack of understanding of a specific concept, include that concept in the weaknesses list.
        - Only include concepts for which there is reasonable evidence of weakness.
        - Do not assume a weakness merely because the answer is incorrect.
        - If there is no clear conceptual weakness, return an empty list.
        - Use the concepts provided in problem_key_concepts whenever possible.

        Return ONLY valid JSON.
        Do not include markdown, explanations, or any text outside the JSON.

        The JSON format must be exactly:

        {
        "is_correct": true,
        "feedback": "",
        "weaknesses": []
        }

        Rules:
        - is_correct must be a boolean.
        - feedback must be a string.
        - weaknesses must be an array of strings.
    """


    human_message = f"""
        Evaluate the student's answer using the following information.

        problem:
        {problem}

        correct_answer:
        {correct_answer}

        answer:
        {answer}

        problem_key_concepts:
        {problem_key_concepts}


        *답변은 한글로 부탁해
    """

    messages = [
            SystemMessage(content=system_message),
            HumanMessage(content=human_message)
    ]

    result = llm.invoke(messages)
    print(result)
    return {}




    