"""initial schema

Revision ID: cdc221221e81
Revises: 
Create Date: 2026-08-14 09:29:25.475752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc221221e81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum', native_enum=False), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.CheckConstraint('grade >= 1 AND grade <= 12', name='ck_student_grade_range'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_table('term',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('term', sa.Enum('1학기', '2학기', '여름방학', '겨울방학', name='term_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.CheckConstraint('grade >= 1 AND grade <= 12', name='ck_term_grade_range'),
    sa.PrimaryKeyConstraint('term_id'),
    sa.UniqueConstraint('grade', 'term', name='uq_term_grade_term')
    )
    op.create_table('curriculum',
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=200), nullable=False),
    sa.Column('step_desc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['term.term_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('curriculum_id'),
    sa.UniqueConstraint('subject_id', 'term_id', 'step', name='uq_curriculum_subject_term_step')
    )
    op.create_table('problem',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.curriculum_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_table('weakness',
    sa.Column('weakness_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=True),
    sa.Column('weakness_keyword', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.curriculum_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('weakness_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'push', name='channel_enum', native_enum=False), server_default='email', nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'opened', name='notification_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='발송 완료 시각'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시 (soft delete)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자 (system/teacher/admin 등)'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('weakness')
    op.drop_table('problem')
    op.drop_table('curriculum')
    op.drop_table('term')
    op.drop_table('subject')
    op.drop_table('student')
    # ### end Alembic commands ###
